### ISSUE TITLE
siunitx for units

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy-v1.0-paper#100]
Paper writes units by hand, we should use siunitx for proper and easier unit typesetting

**Comment by adonath** [comment]
https://github.com/gammapy/gammapy-v1.0-paper/commit/85fbc169ec6edbbde61914e2662e4bce523b65c1 Contais the refactoring to use `siunitx`, there is the small caveat that `tectonic` does not support a more recent version of `siunitx`, so I had to stick to the old API.
