### ISSUE TITLE
Mention the joint crab paper and the Crab data releases by the other experiments

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy-v1.0-paper#101]
The introduction only mentions the HESS data release.

The joint crab paper much better highlights Gammapy's goal of multi instrument analysis, so it should be included.

**Comment by adonath** [comment]
Agreed this should be mentioned in the introduction along with the HAWC and HESS validation papers.

**Comment by adonath** [comment]
Done in #137.
