### ISSUE TITLE
Variability significance

### ISSUE THREAD

**Issue by JohannesBuchner** [gammapy/gammapy-v1.0-paper#102]
I've been invited to join the paper due to this PR: https://github.com/gammapy/gammapy/pull/3252

At the moment, the paper does no variability analysis. But it may be a very small change to add this.

In "Fig. 14. Binned light-curves", the corner of the figure could state the fractional variance and its uncertainty (gammapy.stats.variability.compute_fvar) and in the text could cite https://ui.adsabs.harvard.edu/abs/2003MNRAS.345.1271V for the necessary formulas for this variability quantification taking into account measurement uncertainties.

I am not sure why https://docs.gammapy.org/1.0/api-reference/stats.html does not list the variability sub-package? Or is that functionality intended to be removed in/after 1.0 (if so, my PR probably does not qualify me as a co-author).

**Comment by adonath** [comment]
Thanks @JohannesBuchner for the comments!

> I am not sure why https://docs.gammapy.org/1.0/api-reference/stats.html does not list the variability sub-package? Or is that functionality intended to be removed in/after 1.0 (if so, my PR probably does not qualify me as a co-author).

I think this is basically a bug. Previously those methods lived in `gammapy.time`, which we resolved in favor of organizing the package by data level. I remember we were unsure about the API of those kind of methods so we just moved it to the general `gammapy.stats` subpackage. In general those kind of functionality will remain and is a desired feature it is just completely underrepresented in the docs right now...

> In "Fig. 14. Binned light-curves", the corner of the figure could state the fractional variance and its uncertainty (gammapy.stats.variability.compute_fvar) and in the text could cite https://ui.adsabs.harvard.edu/abs/2003MNRAS.345.1271V for the necessary formulas for this variability quantification taking into account measurement uncertainties.

In addition we could also mention it in the `gammapy.stats` sub-section, which we currently don't.

**Comment by adonath** [comment]
And reminder to myself: improving support for variability estimation is on the roadmap for v2.0. So if this is not mentioned in the paper outlook yet, then it should be mentioned.

**Comment by JohannesBuchner** [comment]
Maybe you could also document how to pass on a gammapy-created data series to Stingray https://docs.stingray.science/notebooks/Powerspectrum/Powerspectrum_tutorial.html#1.-Create-a-light-curve 

This would improve the ecosystem's connections.

**Comment by adonath** [comment]
Let's quickly discuss this at the coding sprint.

**Comment by adonath** [comment]
So we could re-construct that the variability methods in `gammapy.stats` where considered useful, but there was some concern on the validity of those methods for very low counts data. That's why they are currently hidden and only used by some experts. We decided to keep his for now, but time analysis and variability estimation will be a big topic for Gammapy v2.0 (see also https://github.com/gammapy/gammapy/pull/4388). So we extend the statements in the outlook. See #135 and https://github.com/gammapy/gammapy-v1.0-paper/commit/8788fcedd294edae993975b6705d2c64b2125924.

**Comment by JohannesBuchner** [comment]
FYI, for the low counts regime I have reviewed methods here: https://arxiv.org/abs/2106.14529 and also presented [bexvar](https://github.com/JohannesBuchner/bexvar/).
