### ISSUE TITLE
Review of Matthias Fuessling

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy-v1.0-paper#104]
Dear all,

Congratulations for the excellent paper! Please find my annotated version in the attachment.

The majority of my comments are typos etc. except a few suggestions / clarifications:
- mentioning of FAIR principles and FAIR4S
- mentioning of VODF and evolution of GADF
- clarification of "Gammapy is not part of any instrument" vs. "Gammapy has been chosen as base of the CTAO science analysis tool"

I was wondering if one should add one sub-section on the ‘release’ in Section 5. You now talk about the release cycle, but not so much about the steps that lead towards a release of a new version, i.e. the automated verification procedures that are done before a new version is released.

Here is the annotated pdf: [MF.pdf](https://github.com/gammapy/gammapy-v1.0-paper/blob/main/reviews/collaboration/ms-MF_v2.pdf)

**Comment by adonath** [comment]
The PDF is in the repo here: https://github.com/gammapy/gammapy-v1.0-paper/blob/main/reviews/collaboration/ms-MF_v2.pdf

We will keep this issue open to list inline response.

**Comment by adonath** [comment]
Addressed by #126.
