### ISSUE TITLE
How old is gamma-ray astronomy?

### ISSUE THREAD

**Issue by kbruegge** [gammapy/gammapy-v1.0-paper#109]
As reader outside the field the first sentence in the intro begs for more details or a source. Either remove it or add more information maybe? 

Line 2 in Section 1

**Comment by adonath** [comment]
Agreed, could be just removed...

**Comment by adonath** [comment]
https://github.com/gammapy/gammapy-v1.0-paper/commit/fa1f38b20684debf949cf801898f4eaa46e7be97
