### ISSUE TITLE
Fix display of units in Equation 1

### ISSUE THREAD

**Issue by kbruegge** [gammapy/gammapy-v1.0-paper#110]
Line 148 the units are shown in square brackets. I think formally speaking this is wrong. We could simply write it in prose such as 
> something something mathematcal expression given in units of TeV cm erg Ly wahtever. 

Or use the mathematically correct way and divide by the unit using `/`

**Comment by bkhelifi** [comment]
You're right.
We have mix our convention for plots and the paper writing.

**Comment by kbruegge** [comment]
Indeed. the units on the plot axis are also wrong. We shoudl probably stick to the proper ISO supported standard throughout. I think it ISO 31-0? It might have been superseeded? @maxnoe might know more.

**Comment by adonath** [comment]
I don't have any strong preference here, for consistency I'd be happy to change to `value / unit` everywhere...

**Comment by adonath** [comment]
Related  issue #100

**Comment by maxnoe** [comment]
The correct usage (according to the BiPM) for equation 1 would be to use the square brackets as the "unit operator", i.e.:

$$
\Phi = ..., [\Phi] = \mathrm{m}^{-1} \mathrm{s}^{-1} \mathrm{TeV}^{-1}
$$

**Comment by adonath** [comment]
I'll address the unit formatting using siunitx in a different commit.
