### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by anetasie** [gammapy/gammapy-v1.0-paper#111]
Introduction would benefit from a paragraph (maybe even the first one in the paper) stating the importance of the gamma-rays in studies of the universe at the extreme energies, with some references to the recent results from Fermi, HESS, Magic.  It would be a good motivation for the efforts behind making the analysis software that everyone can use.

**Comment by adonath** [comment]
This we still need to address, @registerrier or @adonath?

**Comment by adonath** [comment]
See #138. Please let me know if you have further comments.
