### ISSUE TITLE
Turn figure 16 into a donut?

### ISSUE THREAD

**Issue by kbruegge** [gammapy/gammapy-v1.0-paper#114]
Might improve readability. On the other hand I'm not sure it adds any important information to the text. Maybe we can remove it as well.

**Comment by adonath** [comment]
Here is a proposed alternative version:

<img width="451" alt="image" src="https://user-images.githubusercontent.com/3715928/223158489-a5bff448-1eab-4909-a5cf-147e86da47cd.png">

I think it improves readability, adds the information on the total LOC and reduces white areas.

**Comment by adonath** [comment]
I committed the changes in #125. Please let me know if you have further comments. I'd be happy to address those in a follow-up PR.

**Comment by kbruegge** [comment]
Looks way better. Thanks :+1:
