### ISSUE TITLE
Redundancy in description of gammapy.data and IRFs

### ISSUE THREAD

**Issue by kbruegge** [gammapy/gammapy-v1.0-paper#115]
I feel like lines 311 and following repeat some statements made in the paragraph before and the section 3.3. Maybe all these sections can be shortened to highlight the key functionalities the software provides within the packages/ subpackages.

Maybe at this point of the paper the physical details and much of the prose distract from the core message.

**Comment by kbruegge** [comment]
In section 3.3.2 there are references to class names such as "PSFKing" which are very specific to gamma-ray analysis know how and less to how the software is structured.

**Comment by kbruegge** [comment]
Lines 373 and following re-iterate what the `mu` function is which ahs been described in a previous section.

**Comment by kbruegge** [comment]
Maybe we it would help to write a more detailed but still rather high level description of the typical data analysis in section 2 and just focus on the software in section 3. Details on how to analyse what types of source and what PSFs are maybe not needed in the context of this paper?

**Comment by adonath** [comment]
I think in general we should make sure to not repeat or describe any "theory" in the Gammapy package section. There might be small exceptions e.g. stating the difference between the radial symmetric and FoV coordinate background.
