### ISSUE TITLE
Rephrase "normalization" of likelihoods in 3.7

### ISSUE THREAD

**Issue by kbruegge** [gammapy/gammapy-v1.0-paper#116]
So it's been a while since I did this stuff so this might be stupid. 

In line 537 and following 

>  In Gammapy, the fit statistics are Poisson log-likelihood functions normalized like chi-squares, i.e., they follow the expression 2 log L, where L is the likelihood function used

I suppose you're talking about Wilks Theorem which is a useful assumption when trying to interpret your likelihood in terms of "significance" or something. See https://stephens999.github.io/fiveMinuteStats/wilks.html.  Maybe we can rephrase it that way in the paper.

However maybe for the intended audience of this paper this is useless implementation detail anyways. So it could be removed as well.

**Comment by adonath** [comment]
I agree, I think the appropriate description is something like "...difference in log-likelihood approaches as Chi2 distribution..."

**Comment by registerrier** [comment]
I think this is not only a question of hypothesis testing (Wilks theorem) but also a question of how to derive errors from the fit statistic profiles and the hessian matrix.
`normalized as chi-square` is indeed not a very good wording. So what about simply writing `the fit statistics are  log-likelihood functions multiplied by two`. 
A possible reference for this choice is of course the Cash paper or the minuit manual:
http://www.fresco.org.uk/minuit/cern/node31.html
