### ISSUE TITLE
Sherpa citation

### ISSUE THREAD

**Issue by anetasie** [gammapy/gammapy-v1.0-paper#118]
Additional citations for Sherpa - original description/design and the Zenodo for the software.

@INPROCEEDINGS{2001SPIE.4477...76F,
       author = {{Freeman}, Peter and {Doe}, Stephen and {Siemiginowska}, Aneta},
        title = "{Sherpa: a mission-independent data analysis application}",
     keywords = {Astrophysics},
    booktitle = {Astronomical Data Analysis},
         year = 2001,
       editor = {{Starck}, Jean-Luc and {Murtagh}, Fionn D.},
       series = {Society of Photo-Optical Instrumentation Engineers (SPIE) Conference Series},
       volume = {4477},
        month = nov,
        pages = {76-87},
          doi = {10.1117/12.447161},
archivePrefix = {arXiv},
       eprint = {astro-ph/0108426},
 primaryClass = {astro-ph},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2001SPIE.4477...76F},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

@software{sherpa_2022_7186379,
  author       = {Doug Burke and
                  Omar Laurino and
                  wmclaugh and
                  dtnguyen2 and
                  Hans Moritz Günther and
                  Marie-Terrell and
                  Aneta Siemiginowska and
                  Jamie Budynkiewicz and
                  Harlan Cheer and
                  Tom Aldcroft and
                  Christoph Deil and
                  Brigitta Sipőcz and
                  Johannes Buchner and
                  Axel Donath and
                  Iva Laginja and
                  Katrin Leinweber and
                  nplee and
                  Todd},
  title        = {sherpa/sherpa: Sherpa 4.15.0},
  month        = oct,
  year         = 2022,
  publisher    = {Zenodo},
  version      = {4.15.0},
  doi          = {10.5281/zenodo.7186379},
  url          = {https://doi.org/10.5281/zenodo.7186379}
}

**Comment by adonath** [comment]
Thanks @anetasiem, we do not actually use the software in the paper. But I'll add the first reference...
