### ISSUE TITLE
Comments from Marianne Lemoine-Goumard

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy-v1.0-paper#120]
Very nice and complete paper! Congrats...

* Some possible typos:
  - l115: n => on
  - l763: "with by" => "with"

* Some questions
  - About fig 4 on the LAT PSF: the used one seems worse than the one published in the LAT collaboration (https://www.slac.stanford.edu/exp/glast/groups/canda/lat_Performance_files/gPsfAve68Energy_P8R3_SOURCE_V3psf_10MeV.png). From the LAT, the 68% PSF is about 0.11° at 10 GeV, and in this figure it seems that it is 0.15° at 10 GeV.. Can you check again this quantity?

**Comment by adonath** [comment]
> l115: n => on
> l763: "with by" => "with"

Both were found by other previous reviews, fixed.

**Comment by adonath** [comment]
The remaining comment on Fig 1 I'll add to #124.
