### ISSUE TITLE
Fermipy

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy-v1.0-paper#121]
We have mentioned that we are affiliated to some libraries, that some libraries can use Gammapy with wrappers. But we have not mentioned that some libraries are affiliated to us.
I am thinking about Fermipy that uses our `Maps` sub-packages. Should we add this?

**Comment by adonath** [comment]
I agree, we should mention this. I think we do not have a systematic use of Gammapy as dependency to other packages so the best thing might be not just mention it in the `gammapy.maps` section.
