### ISSUE TITLE
Figure 1 legend covering Fermi-LAT's effective area

### ISSUE THREAD

**Issue by cosimoNigro** [gammapy/gammapy-v1.0-paper#124]
The only comment by Jose Luis not related to grammar was to improve Figure 1.
Currently the legend covers the effective area of Fermi-LAT, which is difficult to see.

**Comment by adonath** [comment]
Another comment by Marianne Lemoine-Goumard:

> About fig 4 on the LAT PSF: the used one seems worse than the one published in the LAT collaboration (https://www.slac.stanford.edu/exp/glast/groups/canda/lat_Performance_files/gPsfAve68Energy_P8R3_SOURCE_V3psf_10MeV.png). From the LAT, the 68% PSF is about 0.11° at 10 GeV, and in this figure it seems that it is 0.15° at 10 GeV.. Can you check again this quantity?

**Comment by adonath** [comment]
Addressed by #132.
