### ISSUE TITLE
Add a reproducibility section

### ISSUE THREAD

**Issue by cosimoNigro** [gammapy/gammapy-v1.0-paper#20]
I think it would be proper to describe in the paper the effort taken to make it reproducible.

It might be a small (sub)section before the conclusion in which the reproducibility assets associated with the paper are discussed:
- this repository;
- the showyourwork format;
- the scripts producing the figures (and their associated links).

**Comment by adonath** [comment]
I agree it is useful to highlight this in a separate section!

**Comment by adonath** [comment]
I think this is still important, I'll add at least short section for nor now...

**Comment by adonath** [comment]
For now it is included here https://github.com/gammapy/gammapy-v1.0-paper/pull/52
