### ISSUE TITLE
Add a figure displaying contributions and citations numbers

### ISSUE THREAD

**Issue by cosimoNigro** [gammapy/gammapy-v1.0-paper#24]
I find this figure displayed in the README of [this package for seismology](https://github.com/obspy/obspy#impact) a good inspiration for a figure to be added to the `Gammapy` paper illustrating contributions and citations.

**Comment by adonath** [comment]
Agreed to not put this for v1.0, but it could be part of the standard Gammapy `README.md` or be shown on the webpage and updated regularly.
