### ISSUE TITLE
Adapt Applications section according to use case

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy-v1.0-paper#25]
We discussed in the call that it might be better to adapt the Application section according to the science use cases rather than the instruments. We should use different instruments data in different cases to cover the variety.

A proposal for the subsections:
- Spectral analysis (use CTA 1 DC galactic centre data)
- 3D analysis (use HESS MSH 15-52)
- Simulations (use CTA prod5 IRFs): What is a good source to simulate?
- Source Detections (Fermi GC)
- Temporal analysis (PKS 2155-304 flare with LightCurveEstimator): Also show temporal models? Using simulations?
- Multi-Instrument fitting (Joint Crab)
- Population studies (GPS population study as done by @QRemy): Also mention analysis on clusters.
- Fitting using physical models (Using Naima models, refer to agnpy): Can be done on joint crab data, or on some flux points from 4FGL + HGPS (the latter makes it clear that fitting only with published data is possible, and also gives usage example for Gammapy.catalogs).

**Comment by adonath** [comment]
Thanks @AtreyeeS for the overview and proposal!

I just have one general comment: if possibly I think we should to limit ourselves to <4-5 examples, not more. However we can try to combine multiple use cases into one example:
- Fitting a physical model to multiple instruments
- The current 1D spectral analysis example for CTA could be extended for simulation as well

**Comment by AtreyeeS** [comment]
Maybe the plots of lightcurve, TS maps, and spectra (everything done by classical analysis) and be referred to from the API sections, and this section only shows the "advanced" examples?

**Comment by adonath** [comment]
I think the TS maps and source detection naturally goes together as well. Possibly over plotting data from `gammapy.catalog` as well...

**Comment by adonath** [comment]
Thanks @AtreyeeS, nothing left to do here!
