### ISSUE TITLE
List of scientific papers using gammapy

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy-v1.0-paper#54]
We need to provide a few references showing the maturity of gammapy for science usage. There can be a few general more shiny examples quoted in the introduction and more package specific examples in the section 3.

The following refereed references mention gammapy (but not necessarily properly cite it).

- Characterization of the Gamma-ray Emission from the Kepler Supernova Remnant with Fermi-LAT
   - https://ui.adsabs.harvard.edu/abs/2022A%26A...660A.129A/abstract
   - A&A 660, A129 (2022)
- Predictions of TeV emission for a set of hard BL Lac objects
   - https://ui.adsabs.harvard.edu/abs/2021MNRAS.508.6128P/abstract
   - Monthly Notices of the Royal Astronomical Society, Volume 508, Issue 4, pp.6128-6141
   - v0.18.2
- Evidence of 100 TeV γ-ray emission from HESS J1702-420: A new PeVatron candidate
    - https://ui.adsabs.harvard.edu/abs/2021A%26A...653A.152A/abstract
    - Astronomy & Astrophysics, Volume 653, id.A152, 21 pp.
    - v0.17
- TeV Emission of Galactic Plane Sources with HAWC and H.E.S.S.
    - https://ui.adsabs.harvard.edu/abs/2021ApJ...917....6A/abstract
    - The Astrophysical Journal, Volume 917, Issue 1, id.6, 16 pp.
    - v0.13 and v0.17
- Systematic evaluation of variability detection methods for eROSITA
    - https://ui.adsabs.harvard.edu/abs/2021arXiv210614529B/abstract
    - A&A special issue eRosita
    - ?
- Revealing x-ray and gamma ray temporal and spectral similarities in the GRB 190829A afterglow
    - https://arxiv.org/abs/2106.02510
    - Science Vol. 372, Issue 6546, pp. 1081-1085 (2021)
    - v0.17
- Cherenkov Telescope Array sensitivity to the putative millisecond pulsar population responsible for the Galactic center excess
    - https://ui.adsabs.harvard.edu/abs/2021arXiv210205648M/abstract
    - v?
- Three-dimensional morphological asymmetries in the ejecta of Cassiopeia A using a component separation method in X-rays 
    - https://ui.adsabs.harvard.edu/abs/2021A%26A...646A..82P/abstract
    - v?
- Optical spectroscopy of Blazars for the Cherenkov Telescope Array
    - https://ui.adsabs.harvard.edu/abs/2020arXiv201205176G/abstract
    - gammapy v0.7
- The Crab nebula variability at short timescales with the Cherenkov Telescope Array
    - https://ui.adsabs.harvard.edu/abs/2020arXiv201108586M/abstract
    - gammapy v0.7
- Prospects for the characterization of the VHE emission from the Crab nebula and pulsar with the Cherenkov Telescope Array
    - https://ui.adsabs.harvard.edu/abs/2020MNRAS.492..708M/abstract
    - gammapy v0.7
- Time-dependent escape of cosmic rays from supernova remnants potentially at the origin of the very-high-energy cosmic-ray gradient of the Galactic center
    - https://ui.adsabs.harvard.edu/abs/2020arXiv201100214J/abstract
    - gammapy v0.17
- Powerful extragalactic jets dissipate their kinetic energy far from the central black hole
    - https://arxiv.org/abs/2010.13670
    - Nature Astronomy 2020
    - gammapy v0.9
- Sensitivity of the Cherenkov Telescope Array for probing cosmology and fundamental physics with gamma-ray propagation
    - https://arxiv.org/abs/2010.01349
    - submitted A&A
    - gammapy v0.11
- Contribution of pulsars to cosmic-ray positrons in light of recent observation of inverse-Compton halos
    - https://ui.adsabs.harvard.edu/abs/2020PhRvD.102b3015M/abstract
    - PRD 2020
    - gammapy v? - population synthesis
- Prospects on high-energy source searches based on pattern recognition Object detection in the H.E.S.S. Galactic Plane Survey and catalogue cross-matches
    - https://ui.adsabs.harvard.edu/abs/2020APh...12202462R/abstract
    - APh 2020
    - gammapy v0.1 ?
- Very high energy γ-ray emission from two blazars of unknown redshift and upper limits on their distance
    - https://ui.adsabs.harvard.edu/abs/2020MNRAS.494.5590A/abstract
    - A&A 2020
    - gammapy v?
- Validation of open-source science tools and background model construction in γ-ray astronomy
    - https://ui.adsabs.harvard.edu/abs/2019A%26A...632A..72M/abstract
    - A&A 2019
    - gammapy v.12
- Towards open and reproducible multi-instrument analysis in gamma-ray astronomy
    - https://ui.adsabs.harvard.edu/abs/2019A%26A...625A..10N/abstract
    - A&A 2019
    - gammapy v0.10?
- Undiscovered Pulsar in the Local Bubble as an Explanation of the Local High Energy Cosmic Ray All-Electron Spectrum
    - https://ui.adsabs.harvard.edu/abs/2018PhRvL.121y1106L/abstract
    - PRL 2018
    - gammapy v? Population synthesis tools.
- The H.E.S.S. Galactic plane survey
    - https://ui.adsabs.harvard.edu/abs/2018A%26A...612A...1H/abstract
    - A&A 2018
    - gammapy v0.6
- A search for new supernova remnant shells in the Galactic plane with H.E.S.S.
    - https://ui.adsabs.harvard.edu/abs/2018A%26A...612A...8H/abstract
    - A&A 2018
    - gammapy v?
- Search for Very-high-energy Emission from Gamma-Ray Bursts Using the First 18 Months of Data from the HAWC Gamma-Ray Observatory
    - https://ui.adsabs.harvard.edu/abs/2017ApJ...843...88A/abstract
    - ApJ 2017

**Comment by adonath** [comment]
Thanks @registerrier, the list seems complete to me!

**Comment by bkhelifi** [comment]
There is also:
- Time-resolved hadronic particle acceleration in the recurrent nova RS Ophiuchi
   - https://www.science.org/doi/10.1126/science.abn0567
   - Science 2022
   - Gammapy V0.19?

**Comment by QRemy** [comment]
CTA GPS proceeding (paper not finished yet)
https://ui.adsabs.harvard.edu/abs/2022icrc.confE.886R/abstract
gammapy v0.17-0.18.2

**Comment by adonath** [comment]
See also #101.

**Comment by adonath** [comment]
@registerrier @bkhelifi @QRemy @AtreyeeS @fabiopintore @cosimoNigro @LauraOlivera please double check whether we should mention any of the papers listed above in the applications example section. Just choose your "favorites", I think the list will never be complete anyway...
