### ISSUE TITLE
Change order of sub package descriptions

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy-v1.0-paper#9]
It is more rational to present sub packages following the analysis data flow. This could start with `gammapy.irf` and `gammapy.data` followed with `gammapy.makers` etc.

`gammapy.maps` could be described first as it is a general structure, or at the DL4 level. 

The last item would be `gammapy.analysis`

**Comment by adonath** [comment]
For now we keep the current structure, but we should review once:
- Whether having datasets before makers makes sense
- And whether IRFs before data is maybe better...
