### ISSUE TITLE
Comments on the v1.0 paper version

### ISSUE THREAD

**Issue by facero** [gammapy/gammapy-v1.0-paper#91]
Hi all

Here are some comments regarding the version compiled on January 30 circulated to the collaboration.

Abstract line 1  : 
"Traditionally, γ-ray astronomy has been conducted by experiments employing proprietary data"
Fermi is a counter example. Maybe saying Cherenkov gamma-ray astronomy (which includes IACTs and Water detectors).

Fig 1
Gammapy logo is still very large maybe reduce it a bit
Concerning the title of figures on the right 
Images => Sky maps ?
SEDs => Spectra 
SED is not defined (defined only in L677) and spectra is more general 

Fig2
SEDs & Lightcurves => Spectra and lightcurves

Minor comments :
L630, L634: IMinuit => iminuit
At least that’s how its referred to in the docs
https://iminuit.readthedocs.io/en/stable/about.html

Fig16: lots of whitespace between figure and caption

L1072 : Not obvious to me why the AstroML package is cited here. Its mostly Machine Learning oriented and not the obvious one to cite for MWL crossmatching.
Looking into the docs AstroML returned no match in the documentation.

L1347: This goes a bit beyond just gammapy but fits within the sentence « has the potential to » :
Unify the community of gamma-ray astronomers, by sharing common tools, DATA FORMATS, and a common vision …

**Comment by adonath** [comment]
Thanks @facero!

**Comment by adonath** [comment]
> Abstract line 1 :
"Traditionally, γ-ray astronomy has been conducted by experiments employing proprietary data"
Fermi is a counter example. Maybe saying Cherenkov gamma-ray astronomy (which includes IACTs and Water detectors).

Changed to "TeV gamma-ray astronomy", I felt "Cherenkov" was maybe a to specific niche expression...

> Fig 1
Gammapy logo is still very large maybe reduce it a bit
Concerning the title of figures on the right
Images => Sky maps ?
SEDs => Spectra
SED is not defined (defined only in L677) and spectra is more general

Addressed all as suggested.

> Fig2
SEDs & Lightcurves => Spectra and lightcurves

Currently this does not fit in a single line. Will keep open for now and address later...

>  L630, L634: IMinuit => iminuit

Done

> Fig16: lots of whitespace between figure and caption

Fixed


> L1072 : Not obvious to me why the AstroML package is cited here. Its mostly Machine Learning oriented and not the obvious one to cite for MWL crossmatching.
Looking into the docs AstroML returned no match in the documentation.

Thanks for checking! For some reason I hand it min there was some cross-match classification algorithms, but I could not find it either. So I just remove the reference.

> L1347: This goes a bit beyond just gammapy but fits within the sentence « has the potential to » :

Agreed. I think in the outlook it is fine to go beyond Gammapy...
