### ISSUE TITLE
Instructions in README

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy-v1.0-paper#92]
According to the instructions in the readme, one should create a new environment from `environment.yml` and activate that.

However, it seems that snakemake anyways creates the a new, separate environment again.

The build then failed with `no such file or directory "clock"`. After installing cloc, the build now fails with:

```
Traceback (most recent call last):
  File "/home/maxnoe/Projects/gammapy-v1.0-paper/src/figures/codestats.py", line 175, in <module>
    main()
  File "/home/maxnoe/Projects/gammapy-v1.0-paper/src/figures/codestats.py", line 166, in main
    result = run_cloc(args)
  File "/home/maxnoe/Projects/gammapy-v1.0-paper/src/figures/codestats.py", line 56, in run_cloc
    PythonAPI = f"PythonAPI                      {files_api}          {blank_api}          {comment_api}          {code_api}"
UnboundLocalError: local variable 'files_api' referenced before assignment
[Wed Feb  1 16:15:36 2023]
Error in rule codestats:
    jobid: 19
    output: src/tables/generated/codestats.tex
    conda-env: /home/maxnoe/Projects/gammapy-v1.0-paper/.snakemake/conda/dc9d9f65a8f32b5ca67f97d6bb598b6c
    shell:
        cd src/figures/ && python codestats.py
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

**Comment by adonath** [comment]
Thanks! It think we can actually remove the dependency on `clock` and just commit the table with the code stats for v1.0, created locally. Now that we have the v1.0 tag, the code stats will not change anymore...

**Comment by adonath** [comment]
I committed the code stat file in https://github.com/gammapy/gammapy-v1.0-paper/commit/b8d46d4aaafa4d1563b20c33490cfba1418c5a6e, this remove the dependency on `cloc`. Please re-open if any issue remains.
