### ISSUE TITLE
Comments on gammapy paper: first draft

### ISSUE THREAD

**Issue by aaguasca** [gammapy/gammapy-v1.0-paper#96]
**Paper draft version**
The first draft version. PDF version sent through Slack on January 30, 2023.

Dear all, the paper reads well and looks great! Congratulations!

Please, find below some minor comments:

Line (L)18: IACT -> IACT**s**
L25: WCD -> WCD**s**
L29: signal to noise -> **signal-to-noise**
L60: IRF -> IRF**s** 
L93: includinf -> includin**g**
L99: common data format the GADF ->  common data format **,** the GADF
L115: based n the -> based **on** the 
between 148-149: field of view -> FoV          | defined in L23
L178: point spread function -> point spread function **(PSF)**
L180, L187, L221, L518, L527, L838: FoV
L378: Gaussian -> Gaussian **profile**
L558: reference to Fig. 8
L678: by a the -> by the
L941: ahve -> have

**Comment by adonath** [comment]
Thanks a lot @aaguasca! I'll start implementing the comments soon...

**Comment by adonath** [comment]
> Line (L)18: IACT -> IACTs

Fixed.

> L25: WCD -> WCDs

Fixed

>L29: signal to noise -> signal-to-noise

Fixed

> L60: IRF -> IRFs

Fixed

> L93: includinf -> including

Fixed in a previous commit.

> L99: common data format the GADF -> common data format , the GADF

Fixed in a previous commit.

> L115: based n the -> based on the

Fixed in a previous commit.

> between 148-149: field of view -> FoV | defined in L23

Fixed

> L178: point spread function -> point spread function (PSF)

Just used PSF, as it was introduced earlier...

> L180, L187, L221, L518, L527, L838: FoV

Fixed.

> L378: Gaussian -> Gaussian profile

Fixed.

> L558: reference to Fig. 8

Fixed in a previous commit.

> L678: by a the -> by the

Fixed in a previous commit.

> L941: ahve -> have

Fixed.

**Comment by adonath** [comment]
Thanks again @aaguasca!
