### ISSUE TITLE
Proper quotation marks

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy-v1.0-paper#99]
The paper code uses ascii `"` everywhere for quotation marks, this produces incorrect english quotation marks in the output.

We should either `use \usepackage[autostyle]{csquotes}` and the `\enquote` command or do it properly by hand:

```
``quotes''
```

**Comment by adonath** [comment]
I also noticed we are not 100% uniform when we use italic text for names. I guess for "slang" we could still use the quotation marks. I'll go through the paper once again...
